// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz0WssUFN71xIAe7zJTSkFVzFYsXUEmeY',
    appId: '1:673446283935:web:697288ff57ce467eac70aa',
    messagingSenderId: '673446283935',
    projectId: 'fitness-app-d0b7f',
    authDomain: 'fitness-app-d0b7f.firebaseapp.com',
    storageBucket: 'fitness-app-d0b7f.appspot.com',
    measurementId: 'G-XTG248FCR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPevD8Qi2SNnPb1soW_GMGIZaXIaAxLec',
    appId: '1:673446283935:android:a905d490419ea3a4ac70aa',
    messagingSenderId: '673446283935',
    projectId: 'fitness-app-d0b7f',
    storageBucket: 'fitness-app-d0b7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeEGH7QTKJj3VXjwmcwtwko24uAi8qf6s',
    appId: '1:673446283935:ios:7f94981f3c452512ac70aa',
    messagingSenderId: '673446283935',
    projectId: 'fitness-app-d0b7f',
    storageBucket: 'fitness-app-d0b7f.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeEGH7QTKJj3VXjwmcwtwko24uAi8qf6s',
    appId: '1:673446283935:ios:7f94981f3c452512ac70aa',
    messagingSenderId: '673446283935',
    projectId: 'fitness-app-d0b7f',
    storageBucket: 'fitness-app-d0b7f.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz0WssUFN71xIAe7zJTSkFVzFYsXUEmeY',
    appId: '1:673446283935:web:c1b712670235d5dfac70aa',
    messagingSenderId: '673446283935',
    projectId: 'fitness-app-d0b7f',
    authDomain: 'fitness-app-d0b7f.firebaseapp.com',
    storageBucket: 'fitness-app-d0b7f.appspot.com',
    measurementId: 'G-W7FH2DJQMW',
  );
}
